name: flutter_user_agent
description: Retrieve Android/iOS device user agents.
version: 0.0.1
author: j0j00 <jojodev@protonmail.com>
homepage: https://github.com/j0j00/flutter_user_agent

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.jojodev.flutter.flutteruseragent
    pluginClass: FlutterUserAgentPlugin